version: "3.4"

services:
  webapp:
    restart: always
    image: htkuan/webapp
    build: ./webapp
#    command: python manage.py runserver 0.0.0.0:8000
    command: gunicorn webapp.wsgi:application -b 0.0.0.0:8000
    volumes:
      - ./webapp:/app/

  webserver:
    restart: always
    image: htkuan/webserver:load
    build: ./webserver
    ports:
      - "8000:8000"
    links:
      - webapp
    depends_on:
      - webapp
