version: "3.4"

services:
  webapp:
    restart: always
    image: htkuan/webapp:lb
    build: ./webapp
#    command: python manage.py runserver 0.0.0.0:8000
    command: gunicorn webapp.wsgi:application -b 0.0.0.0:8000
    environment:
      - APP=webapp_1
    volumes:
      - ./webapp:/app/

  webapp2:
    restart: always
    image: htkuan/webapp:lb
    build: ./webapp
#    command: python manage.py runserver 0.0.0.0:8000
    command: gunicorn webapp.wsgi:application -b 0.0.0.0:8001
    environment:
      - APP=webapp_2
    volumes:
      - ./webapp:/app/

  webserver:
    restart: always
    image: htkuan/webserver:lb
    build: ./webserver
    ports:
      - "8000:80"
    links:
      - webapp
      - webapp2
    depends_on:
      - webapp
      - webapp2
